### ISSUE TITLE
ユーザー情報に文字数制限を追加する

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/musclers#116]
# 概要

ユーザーのdescriptionなどのtextが無制限になっているため、ある程度の長さで制限をつける。
長さは要相談。

# モック・スクリーンショット

新規機能に関するモックやスクリーンショット(AdobeXDで作成した画面等)があれば添付

# 関連issue

- [ ] あればissue番号を

# 留意事項・参考

留意事項や参考があれば

**Comment by kageyasai2** [comment]
nickname: 64文字
description: 1024文字
