### ISSUE TITLE
メールアドレスを入力しなくてもログインできる問題

### ISSUE THREAD

**Issue by various3211workd** [NAKKA-K/musclers#129]
# 概要

SSIA

# 再現方法・発生原因

1. Facebookでログインを押しmailを入力する画面に遷移する
2. homeなど別の画面に移動する
3. ログインできている

# 本来期待する動作概要
略

# スクリーンショット
略

# 関連issue
略

# 留意事項・参考
cache消して試したないけど、本来の挙動考えたら関係ないはず

**Comment by various3211workd** [comment]
バグじゃなくて仕様っぽいのでcloseします

**Comment by NAKKA-K** [comment]
仕様といえば仕様だが、メアドを入力してない場合の対応をするか、ログインできない様にするなどの解決は必要そう。
