### ISSUE TITLE
Railsのテストを書くための勉強をする & 実際にテストを書く

### ISSUE THREAD

**Issue by kageyasai2** [NAKKA-K/musclers#135]
# 概要

Rspecの勉強をしてテストを書けるようになる

# モック・スクリーンショット

# 関連issue

- [ ] あればissue番号を

# 留意事項・参考

勉強をしながら他のタスクも消化していきたい

**Comment by NAKKA-K** [comment]
👍

**Comment by kageyasai2** [comment]
Controllerのテストを書くときはController specではなくrequest specで書くことが推奨されている
https://qiita.com/kino3/items/e09d0fbf15ac9a89ae0e
