### ISSUE TITLE
実際の利用者を想定したテストデータを作成する

### ISSUE THREAD

**Issue by kageyasai2** [NAKKA-K/musclers#258]
# 概要

実際の利用者を想定したテストデータを作成する

全員データ入力の仕事をやって欲しい。
必要なデータは以下の通り。

### @kageyasai2 
- [x] ~ユーザー(21人以上)~
- [x] ~DM(何人かだけに3,4メッセージ)~
- [x] ~DMGroup(3〜5個)~
- [x] ~友達(10人くらい)~
- [x] ~ユーザータグ(0〜3個)~
- [x] ~通知(10件くらい)~(DMの通知だけ作成、その他のグループメッセージの通知のテストデータは出来てから追加する)

### @NAKKA-K 
- [x] ~グループ(10個以上)~
- [x] ~参加機能のためにGroupUser(いくつかのグループに何人か)~

### 未定
- 別Issueに    グループメッセージ(いくつかのグループに5件以上)

### @yokotakento 
- [x] ~ブログ(10件くらい)~
- [x] ~ブログタグ(0~3個)~

密接してるデータを複数人で入力する場合、しっかりと連携を取りながら作成して欲しい。
そして誰がどこを担当するかも報告するように。

**Comment by NAKKA-K** [comment]
@kageyasai2 グループのデータってもう作った？
いま、グループ参加機能を作るためにグループのデータが欲しいんだけど、もう作ってるならそれだけ欲しい。
ないならこっちで作るけど。

**Comment by kageyasai2** [comment]
@NAKKA-K グループはまだ作ってない
ユーザのテストデータだけ @showgoel に作成を頼んだ

**Comment by NAKKA-K** [comment]
じゃあGroupだけこっちで使う分だけ作るね。

まあ、別のGroupを作ってもらっても良いし、GroupUserとかも作ってもらって良いよ。

**Comment by kageyasai2** [comment]
おk

**Comment by NAKKA-K** [comment]
全員データ入力の仕事をやって欲しい。
必要なデータは以下の通り。

### @kageyasai2 
- ~ユーザー(21人以上)~
- ~DM(何人かだけに3,4メッセージ)~
- ~DMGroup(3〜5個)~
- ~友達(10人くらい)~
- ~ユーザータグ(0〜3個)~
- ~通知(10件くらい)~(DMの通知だけ作成、その他のグループメッセージの通知のテストデータは出来てから追加する)

### @NAKKA-K 
- ~グループ(10個以上)~
- ~参加機能のためにGroupUser(いくつかのグループに何人か)~

### 未定
- グループメッセージ(いくつかのグループに5件以上)

### @yokotakento 
- ~ブログ(10件くらい)~
- ~ブログタグ(0~3個)~

密接してるデータを複数人で入力する場合、しっかりと連携を取りながら作成して欲しい。
そして誰がどこを担当するかも報告するように。

**Comment by NAKKA-K** [comment]
グループメッセージだけできてないんだよな。
冬休み中にやっておきたいな
