### ISSUE TITLE
An error occurredが出力される

### ISSUE THREAD

**Issue by various3211workd** [NAKKA-K/musclers#272]
# 概要

バグの概要

# 再現方法・発生原因

1. ログインする
2. Musclersのアイコンをクリックする
3. An error occurred

# 本来期待する動作概要
Home画面への遷移

本来期待する動作
Home画面への遷移

# スクリーンショット

<img width="1411" alt="スクリーンショット 2019-12-06 9 25 12" src="https://user-images.githubusercontent.com/43775946/70285320-792db680-180a-11ea-99b0-ffbda1190b2f.png">

<img width="1411" alt="スクリーンショット 2019-12-06 9 25 27" src="https://user-images.githubusercontent.com/43775946/70285323-7c28a700-180a-11ea-8675-f8b66be32635.png">

# 留意事項・参考

留意事項や参考があれば

**Comment by NAKKA-K** [comment]
migrateとかseedの実行はした？

**Comment by various3211workd** [comment]
した。
もしかして出ない？

**Comment by various3211workd** [comment]
headerのリンク修正するだけだろうからすぐ終わると思うけど

**Comment by NAKKA-K** [comment]
出ないね。
どこに遷移してる？

最新のやつではhttp://localhost:3000/auth/mypage だけど

**Comment by various3211workd** [comment]
他の人に試してもらったけど、自分だけっぽいからissue閉じます
