### ISSUE TITLE
ユーザ詳細APIのレスポンス内容を変更する

### ISSUE THREAD

**Issue by kageyasai2** [NAKKA-K/musclers#42]
- [ ] User.rbに書いてあるenumの値がnot_setの所を空文字に変更する
- [x] 性別、本気度の値を日本語に変換する

**Comment by NAKKA-K** [comment]
> 性別、本気度の値を日本語に変換する

別issueで対応

**Comment by NAKKA-K** [comment]
> User.rbに書いてあるenumの値がnot_setの所を空文字に変更する

I18nで`no_set`を`未設定`に変換しているのでまあいいか
