### ISSUE TITLE
子要素をクリックした時に親要素に波紋が広がる状態を解決する

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/musclers#65]
子要素をクリックした時に親要素に波紋が広がる状態を解決できない......。
バブリングで子要素をクリックした時に親要素のリンクに遷移する問題は解決できたけど、クリック時の波紋はclick.preventでもclick.stopでも消せなかった。

<img width="1680" alt="スクリーンショット 2019-10-03 12 53 05" src="https://user-images.githubusercontent.com/22770924/66099625-8055ff80-e5e2-11e9-964f-dc3fe04a328e.png">

**Comment by kageyasai2** [comment]
解決策１：card自体にリンクを付けるのではなく名前の所をリンクにする
解決策２：友達申請ボタンをcardの外に出す

**Comment by kageyasai2** [comment]
名前の所をリンクにすれば波紋は消える

**Comment by NAKKA-K** [comment]
うーん、それしかないのかな......
最低でも画像、名前はクリックできてほしいから、そこだけに絞るってのも致し方なしか。

**Comment by kageyasai2** [comment]
画像と名前にリンク付けてプルリク出すわ

**Comment by NAKKA-K** [comment]
仕方ないか。了解
