### ISSUE TITLE
ログインページなどのヘッダーにログイン中ユーザーのアイコンが表示されていないので追加する

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/musclers#92]

**Comment by kageyasai2** [comment]
・ログインページだけアイコンが表示されていない

**Comment by kageyasai2** [comment]
参照している画像のURLが違うので参照URLをいじってやれば上手くいきそう
![login](https://user-images.githubusercontent.com/44107494/67654136-e3437800-f98f-11e9-8b1a-446a06650dbc.JPG)

**Comment by kageyasai2** [comment]
ユーザ詳細画面でも同じエラー出てたけどヘッダーにはアイコンが表示されている
![user](https://user-images.githubusercontent.com/44107494/67654602-6d401080-f991-11e9-9e1d-7c4b883863e0.JPG)

**Comment by kageyasai2** [comment]
noimage.pngをフロントエンドじゃなくてバックエンドに配置してやれば動くかも

**Comment by kageyasai2** [comment]
恐らく `pages/` のディレクトリ構成によって `static/images` を参照するURLが変わる？
`pages/auth/login.vue` では `http://localhost/auth/images/noimage.png`
`pages/user/_id.vue`  では `http://localhost/user/images/noimage.png`
`pages/` 直下のファイルから参照した場合は `http://localhost/images/noimage.png` を参照するのでエラーにならない

**Comment by kageyasai2** [comment]
`backend/public/images/` に画像を配置してやることで問題は解決
![headerbug](https://user-images.githubusercontent.com/44107494/67731806-49acb280-f9f1-11e9-95a1-3ba8e99dce1a.JPG)
